//跳转页面
function initJump(){
    //点击首页跳转到default页面
    $(".header").bind("clcik",function(){
        alert(1);
        $.ajax({
            url:"/ssm/decontroller/firstjsp",
            type:"post",
            data:{},
            success:function(data){
                window.location="/ssm/decontroller/default";
            }
        });
    });
    //点击注销，退回到登录页面
    $(".logout").bind("clcik",function(){
        $.ajax({
            url:"/ssm/decontroller/logout",
            type:"post",
            data:{},
            success:function(data){
                window.location="/ssm/decontroller/login";
            }
        });
    });
    //点击后台管理跳转到下一级列表中的用户管理
    $("label:first").bind("click",function(){
        $.ajax({
            url:"/ssm/auUser/getUserByCondition",
            type:"post",
            data:{},
            success:function(data){
                window.location="/ssm/auUser/usermanager";
            }
        });
    });
    //点击用户管理跳转页面
    $("li:eq(0)").bind("click",function(){
        $.ajax({
            url:"/ssm/auUser/getUserByCondition",
            type:"post",
            data:{},
            success:function(data){
                window.location="/ssm/auUser/usermanager";
            }
        });
    });
    //点击角色管理跳转页面
    $("li:eq(1)").bind("click",function(){
        $.ajax({
            url:"/ssm/auRole/rolejsp",
            type:"post",
            data:{},
            success:function(data){
                window.location="/ssm/auRole/rolemanager";
            }
        });
    });
    //点击权限管理跳转页面
    $("li:eq(2)").bind("click",function(){
        $.ajax({
            url:"/ssm/premission/getAllPermission",
            type:"post",
            data:{},
            success:function(data){
                window.location.href="/ssm/premission/getAllPermission";
            }
        });
    });
    //点击基商品套餐管理跳转页面

    //点击商品管理跳转页面
    $("li:eq(3)").bind("click",function(){
        $.ajax({
            url:"/ssm/goodsinfo/goodsjsp",
            type:"post",
            data:{},
            success:function(data){
                window.location="/ssm/goodsinfo/goodsmanager";
            }
        });
    });
    //点击基础信息跳转页面
    $("li:eq(5)").bind("click",function(){
        $.ajax({
            url:"/ssm/basicinfo/basicjsp",
            type:"post",
            data:{},
            success:function(data){
                window.location="/ssm/basicinfo/basicinformation";
            }
        });
    });
    //点击数据字典跳转页面
    $("li:eq(6)").bind("click",function(){
        $.ajax({
            url:"/ssm/datadict/datajsp",
            type:"post",
            data:{},
            success:function(data){
                window.location="/ssm/datadict/datadictionary";
            }
        });
    });
}