function init(){
    $("label:eq(0)").bind("click",function(){
        window.location.href="user.jsp";
    });
    $("label:eq(1)").bind("click",function(){
        window.location.href="scan.jsp";
    });
    $("label:eq(2)").bind("click",function(){
        window.location.href="income.jsp";
    });
    $("label:eq(3)").bind("click",function(){
        window.location.href="permission.jsp";
    });
    $("label:eq(4)").bind("click",function(){
        window.location.href="admin.jsp";
    });
    $("label:last").bind("click",function(){
        window.location.href="factory.jsp";
    });
}